name: Reusable CD Deployment

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      artifactory_path:
        required: true
        type: string
      share_path:
        required: true
        type: string
      share_user:
        required: true
        type: string
      share_password:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: 'stage'
    secrets:
      jfrog_user:
        required: true
      jfrog_password:
        required: true
      jfrog_url:
        required: true

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Log deployment environment
        run: echo "🚀 Deploying to environment: ${{ inputs.environment }}"

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3

      - name: Configure JFrog CLI
        run: |
          jfrog config add myserver `
            --url="${{ secrets.jfrog_url }}" `
            --user="${{ secrets.jfrog_user }}" `
            --password="${{ secrets.jfrog_password }}" `
            --interactive=false

      - name: Download artifact from Artifactory
        run: |
          jfrog rt dl "${{ inputs.artifactory_path }}/${{ inputs.artifact_name }}" --server-id=myserver
          echo "✅ File downloaded: ${{ inputs.artifact_name }}"

      - name: Mount shared drive
        run: |
          net use Z: "${{ inputs.share_path }}" /user:${{ inputs.share_user }} ${{ inputs.share_password }}

      - name: Copy artifact to shared drive
        run: |
          copy "${{ inputs.artifact_name }}" Z:\

      - name: Unmount shared drive
        run: |
          net use Z: /delete
